/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authors_list"];
        put?: never;
        post: operations["authors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authors_retrieve"];
        put?: never;
        post?: never;
        delete: operations["authors_destroy"];
        options?: never;
        head?: never;
        patch: operations["authors_partial_update"];
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["books_list"];
        put?: never;
        post: operations["books_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["books_retrieve"];
        put?: never;
        post?: never;
        delete: operations["books_destroy"];
        options?: never;
        head?: never;
        patch: operations["books_partial_update"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/copies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["books_copies_list"];
        put?: never;
        post: operations["books_copies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put?: never;
        post?: never;
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/v1/copies/{copy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["copies_retrieve"];
        put?: never;
        post?: never;
        delete: operations["copies_destroy"];
        options?: never;
        head?: never;
        patch: operations["copies_partial_update"];
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fines_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fines/{fine_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fines_pay_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fines/{fine_id}/waive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fines_waive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["loans_list"];
        put?: never;
        post: operations["loans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["loans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loan_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loans_renew_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loan_id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loans_return_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["members_partial_update"];
        trace?: never;
    };
    "/api/v1/members/me/fines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_me_fines_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_me_loans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_me_reservations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reservations_list"];
        put?: never;
        post: operations["reservations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reservations_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}/fulfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reservations_fulfil_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthorResponse: {
            id: number;
            name: string;
            bio: string;
            birth_year: number | null;
            death_year: number | null;
            readonly book_count: number;
        };
        AuthorSummaryResponse: {
            id: number;
            name: string;
        };
        AuthorWriteRequestRequest: {
            name: string;
            /** @default  */
            bio: string;
            birth_year?: number | null;
            death_year?: number | null;
        };
        BookCreateRequestRequest: {
            isbn: string;
            title: string;
            /** @default  */
            subtitle: string;
            author_ids?: number[];
            category_id?: number | null;
            /** @default  */
            publisher: string;
            published_year?: number | null;
            /** @default English */
            language: string;
            page_count?: number | null;
            /** @default  */
            description: string;
            cover_url?: string;
        };
        BookListItemResponse: {
            id: number;
            isbn: string;
            title: string;
            subtitle: string;
            authors: components["schemas"]["AuthorSummaryResponse"][];
            category: components["schemas"]["CategorySummaryResponse"] | null;
            published_year: number | null;
            language: string;
            cover_url: string;
            readonly total_copies: number;
            readonly available_copies: number;
        };
        BookResponse: {
            id: number;
            isbn: string;
            title: string;
            subtitle: string;
            authors: components["schemas"]["AuthorSummaryResponse"][];
            category: components["schemas"]["CategorySummaryResponse"] | null;
            publisher: string;
            published_year: number | null;
            language: string;
            page_count: number | null;
            description: string;
            cover_url: string;
            readonly total_copies: number;
            readonly available_copies: number;
            /** Format: date-time */
            created_at: string;
        };
        BookSummaryResponse: {
            id: number;
            title: string;
            isbn: string;
            cover_url: string;
            readonly authors: string[];
        };
        CategoryResponse: {
            id: number;
            name: string;
            slug: string;
            description: string;
            readonly book_count: number;
        };
        CategorySummaryResponse: {
            id: number;
            name: string;
            slug: string;
        };
        CategoryWriteRequestRequest: {
            name: string;
            /** @default  */
            description: string;
        };
        ChangePasswordRequestRequest: {
            current_password: string;
            new_password: string;
        };
        CheckoutRequestRequest: {
            barcode: string;
            member_id: number;
        };
        CopyCreateRequestRequest: {
            barcode: string;
            /** @default  */
            call_number: string;
            /** Format: date */
            acquired_on?: string;
            /** @default  */
            condition_note: string;
            /** Format: decimal */
            replacement_cost?: string | null;
        };
        CopyResponse: {
            id: number;
            book_id: number;
            readonly book_title: string;
            barcode: string;
            call_number: string;
            status: components["schemas"]["CopyStatus"];
            /** Format: date */
            acquired_on: string;
            condition_note: string;
            /** Format: decimal */
            replacement_cost: string | null;
        };
        /**
         * @description * `AVAILABLE` - Available
         *     * `ON_LOAN` - On loan
         *     * `RESERVED` - Reserved
         *     * `LOST` - Lost
         *     * `DAMAGED` - Damaged
         *     * `WITHDRAWN` - Withdrawn
         * @enum {string}
         */
        CopyStatus: "AVAILABLE" | "ON_LOAN" | "RESERVED" | "LOST" | "DAMAGED" | "WITHDRAWN";
        CopySummaryResponse: {
            id: number;
            barcode: string;
            call_number: string;
            status: string;
        };
        DashboardStatsResponse: {
            total_titles: number;
            total_copies: number;
            copies_available: number;
            copies_on_loan: number;
            loans_active: number;
            loans_overdue: number;
            loans_due_today: number;
            active_members: number;
            suspended_members: number;
            reservations_waiting: number;
            reservations_ready: number;
            /** Format: decimal */
            unpaid_fines_total: string;
            unpaid_fines_count: number;
        };
        /**
         * @description * `OVERDUE` - Overdue
         *     * `DAMAGE` - Damage
         *     * `LOST` - Lost
         * @enum {string}
         */
        FineReason: "OVERDUE" | "DAMAGE" | "LOST";
        FineResponse: {
            id: number;
            loan_id: number;
            member: components["schemas"]["MemberSummaryResponse"];
            readonly book_title: string;
            /** Format: decimal */
            amount: string;
            reason: components["schemas"]["FineReason"];
            status: string;
            /** Format: date */
            assessed_on: string;
            /** Format: date-time */
            paid_at: string | null;
            /** Format: date-time */
            waived_at: string | null;
            waiver_reason: string;
        };
        LoanResponse: {
            id: number;
            book: components["schemas"]["BookSummaryResponse"];
            copy: components["schemas"]["CopySummaryResponse"];
            member: components["schemas"]["MemberSummaryResponse"];
            /** Format: date-time */
            checked_out_at: string;
            /** Format: date */
            due_on: string;
            /** Format: date-time */
            returned_at: string | null;
            renewal_count: number;
            is_active: boolean;
            is_overdue: boolean;
            days_overdue: number;
        };
        LoginRequestRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LogoutRequestRequest: {
            refresh: string;
        };
        MemberListItemResponse: {
            id: number;
            /** Format: email */
            email: string;
            full_name: string;
            membership_number: string;
            is_active: boolean;
            is_suspended: boolean;
            /** Format: date */
            membership_expires_on: string | null;
            readonly active_loan_count: number;
            /** Format: decimal */
            readonly unpaid_fine_total: string;
        };
        MemberSummaryResponse: {
            id: number;
            /** Format: email */
            email: string;
            full_name: string;
            /** @default  */
            membership_number: string;
        };
        /** @description For endpoints whose only useful answer is 'it worked'. */
        MessageResponse: {
            detail: string;
        };
        PatchedAuthorWriteRequestRequest: {
            name?: string;
            /** @default  */
            bio: string;
            birth_year?: number | null;
            death_year?: number | null;
        };
        /** @description Same field set; every field optional so ``PATCH`` behaves. */
        PatchedBookUpdateRequestRequest: {
            isbn?: string;
            title?: string;
            /** @default  */
            subtitle: string;
            author_ids?: number[];
            category_id?: number | null;
            /** @default  */
            publisher: string;
            published_year?: number | null;
            /** @default English */
            language: string;
            page_count?: number | null;
            /** @default  */
            description: string;
            cover_url?: string;
        };
        PatchedCategoryWriteRequestRequest: {
            name?: string;
            /** @default  */
            description: string;
        };
        PatchedCopyUpdateRequestRequest: {
            call_number?: string;
            status?: components["schemas"]["CopyStatus"];
            condition_note?: string;
            /** Format: decimal */
            replacement_cost?: string | null;
        };
        /** @description Librarian-only changes to someone else's membership. */
        PatchedMemberUpdateRequestRequest: {
            is_suspended?: boolean;
            suspension_reason?: string;
            /** Format: date */
            membership_expires_on?: string | null;
            is_active?: boolean;
            phone?: string;
            address?: string;
        };
        /** @description Fields a user may change about themselves. Role and status are deliberately absent. */
        PatchedUpdateMeRequestRequest: {
            first_name?: string;
            last_name?: string;
            phone?: string;
            address?: string;
        };
        RefreshRequest: {
            refresh: string;
        };
        RefreshRequestRequest: {
            refresh: string;
        };
        RegisterRequestRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @default  */
            first_name: string;
            /** @default  */
            last_name: string;
            /** @default  */
            phone: string;
            /** @default  */
            address: string;
        };
        ReservationCreateRequestRequest: {
            book_id: number;
            member_id?: number;
        };
        ReservationResponse: {
            id: number;
            book: components["schemas"]["BookSummaryResponse"];
            member: components["schemas"]["MemberSummaryResponse"];
            status: components["schemas"]["ReservationStatus"];
            /** Format: date-time */
            reserved_at: string;
            /** Format: date-time */
            ready_at: string | null;
            /** Format: date */
            expires_on: string | null;
            queue_position: number;
            held_copy: components["schemas"]["CopySummaryResponse"] | null;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `READY` - Ready for collection
         *     * `FULFILLED` - Fulfilled
         *     * `CANCELLED` - Cancelled
         *     * `EXPIRED` - Expired
         * @enum {string}
         */
        ReservationStatus: "PENDING" | "READY" | "FULFILLED" | "CANCELLED" | "EXPIRED";
        ReturnResponse: {
            loan: components["schemas"]["LoanResponse"];
            readonly fine: {
                [key: string]: unknown;
            } | null;
            readonly hold: {
                [key: string]: unknown;
            } | null;
            copy_status: string;
            readonly message: string;
        };
        TokenResponse: {
            access: string;
            refresh: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            id: number;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            full_name: string;
            role: components["schemas"]["UserRole"];
            is_active: boolean;
            /** Format: date-time */
            date_joined: string;
            readonly profile: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description * `LIBRARIAN` - Librarian
         *     * `MEMBER` - Member
         * @enum {string}
         */
        UserRole: "LIBRARIAN" | "MEMBER";
        WaiveFineRequestRequest: {
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequestRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequestRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateMeRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateMeRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateMeRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshRequestRequest"];
                "multipart/form-data": components["schemas"]["RefreshRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequestRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    authors_list: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorResponse"][];
                };
            };
        };
    };
    authors_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorWriteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthorWriteRequestRequest"];
                "multipart/form-data": components["schemas"]["AuthorWriteRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorResponse"];
                };
            };
        };
    };
    authors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorResponse"];
                };
            };
        };
    };
    authors_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authors_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAuthorWriteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAuthorWriteRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedAuthorWriteRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorResponse"];
                };
            };
        };
    };
    books_list: {
        parameters: {
            query?: {
                author?: number;
                available?: boolean;
                category?: number;
                language?: string;
                ordering?: "-created_at" | "-published_year" | "-title" | "created_at" | "published_year" | "title";
                /** @description Title, subtitle, ISBN or author name */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListItemResponse"][];
                };
            };
        };
    };
    books_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BookCreateRequestRequest"];
                "multipart/form-data": components["schemas"]["BookCreateRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    books_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    books_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    books_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBookUpdateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBookUpdateRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedBookUpdateRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    books_copies_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"][];
                };
            };
        };
    };
    books_copies_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyCreateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CopyCreateRequestRequest"];
                "multipart/form-data": components["schemas"]["CopyCreateRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWriteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryWriteRequestRequest"];
                "multipart/form-data": components["schemas"]["CategoryWriteRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryWriteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryWriteRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryWriteRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    copies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                copy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"];
                };
            };
        };
    };
    copies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                copy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                copy_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCopyUpdateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCopyUpdateRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedCopyUpdateRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"];
                };
            };
        };
    };
    dashboard_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsResponse"];
                };
            };
        };
    };
    fines_list: {
        parameters: {
            query?: {
                member?: number;
                status?: "outstanding" | "paid" | "waived";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FineResponse"][];
                };
            };
        };
    };
    fines_pay_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FineResponse"];
                };
            };
        };
    };
    fines_waive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fine_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaiveFineRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WaiveFineRequestRequest"];
                "multipart/form-data": components["schemas"]["WaiveFineRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FineResponse"];
                };
            };
        };
    };
    loans_list: {
        parameters: {
            query?: {
                book?: number;
                member?: number;
                /** @description Barcode, title, email or membership number */
                search?: string;
                status?: "active" | "overdue" | "returned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"][];
                };
            };
        };
    };
    loans_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutRequestRequest"];
                "multipart/form-data": components["schemas"]["CheckoutRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
        };
    };
    loans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
        };
    };
    loans_renew_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
        };
    };
    loans_return_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnResponse"];
                };
            };
        };
    };
    members_list: {
        parameters: {
            query?: {
                is_suspended?: boolean;
                /** @description Email, name or membership number */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListItemResponse"][];
                };
            };
        };
    };
    members_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMemberUpdateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMemberUpdateRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedMemberUpdateRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    members_me_fines_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FineResponse"][];
                };
            };
        };
    };
    members_me_loans_list: {
        parameters: {
            query?: {
                status?: "active" | "overdue" | "returned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"][];
                };
            };
        };
    };
    members_me_reservations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"][];
                };
            };
        };
    };
    reservations_list: {
        parameters: {
            query?: {
                book?: number;
                /** @description Librarians only */
                member?: number;
                status?: "CANCELLED" | "EXPIRED" | "FULFILLED" | "PENDING" | "READY" | "active";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"][];
                };
            };
        };
    };
    reservations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreateRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReservationCreateRequestRequest"];
                "multipart/form-data": components["schemas"]["ReservationCreateRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    reservations_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    reservations_fulfil_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
        };
    };
}
