# Generated by Django 6.1 on 2026-08-16 07:38

import domains.catalog.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True, validators=[domains.catalog.validators.validate_isbn])),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=180)),
                ('published_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('language', models.CharField(db_index=True, default='English', max_length=40)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='catalog.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('call_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On loan'), ('RESERVED', 'Reserved'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='AVAILABLE', max_length=16)),
                ('acquired_on', models.DateField(default=django.utils.timezone.localdate)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book')),
            ],
            options={
                'verbose_name_plural': 'book copies',
                'ordering': ('book__title', 'barcode'),
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'published_year'], name='catalog_boo_title_a10653_idx'),
        ),
    ]
