"""Every error code the API can return, in one place.

Adding a code here and documenting it in ``docs/api-errors.md`` is part of the definition
of done for any new failure mode.
"""

# Generic
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
PERMISSION_DENIED = "PERMISSION_DENIED"
METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
THROTTLED = "THROTTLED"
CONFLICT = "CONFLICT"
INTERNAL_ERROR = "INTERNAL_ERROR"

# accounts
EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
NOT_A_MEMBER = "NOT_A_MEMBER"

# catalog
BOOK_HAS_COPIES = "BOOK_HAS_COPIES"
COPY_ON_LOAN = "COPY_ON_LOAN"
AUTHOR_HAS_BOOKS = "AUTHOR_HAS_BOOKS"
CATEGORY_HAS_BOOKS = "CATEGORY_HAS_BOOKS"
DUPLICATE_ISBN = "DUPLICATE_ISBN"
DUPLICATE_BARCODE = "DUPLICATE_BARCODE"

# circulation
COPY_NOT_AVAILABLE = "COPY_NOT_AVAILABLE"
LOAN_LIMIT_REACHED = "LOAN_LIMIT_REACHED"
MEMBERSHIP_SUSPENDED = "MEMBERSHIP_SUSPENDED"
MEMBERSHIP_EXPIRED = "MEMBERSHIP_EXPIRED"
UNPAID_FINES = "UNPAID_FINES"
COPY_HELD_FOR_OTHER_MEMBER = "COPY_HELD_FOR_OTHER_MEMBER"
LOAN_ALREADY_RETURNED = "LOAN_ALREADY_RETURNED"
RENEWAL_LIMIT_REACHED = "RENEWAL_LIMIT_REACHED"
RENEWAL_BLOCKED_OVERDUE = "RENEWAL_BLOCKED_OVERDUE"
RENEWAL_BLOCKED_RESERVED = "RENEWAL_BLOCKED_RESERVED"
DUPLICATE_RESERVATION = "DUPLICATE_RESERVATION"
ALREADY_ON_LOAN_BY_MEMBER = "ALREADY_ON_LOAN_BY_MEMBER"
RESERVATION_NOT_ACTIVE = "RESERVATION_NOT_ACTIVE"
RESERVATION_NOT_READY = "RESERVATION_NOT_READY"
NO_COPY_AVAILABLE = "NO_COPY_AVAILABLE"
FINE_ALREADY_SETTLED = "FINE_ALREADY_SETTLED"
